version: '3.8'

services:
  porter:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - porter_data:/data
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - PORT=9000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  porter_data:
    driver: local