name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test -v -race -coverprofile=coverage.out ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out

  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.x

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        go build -o porter-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/porter

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: porter-${{ matrix.goos }}-${{ matrix.goarch }}
        path: porter-${{ matrix.goos }}-${{ matrix.goarch }}

  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          porterfs/porter:latest
          porterfs/porter:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  integration-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.x

    - name: Download Linux binary
      uses: actions/download-artifact@v3
      with:
        name: porter-linux-amd64

    - name: Make binary executable
      run: chmod +x porter-linux-amd64

    - name: Build test client
      run: go build -o test-client ./cmd/test-client

    - name: Run integration tests
      run: |
        # Start server in background
        ./porter-linux-amd64 -config config.yaml.example &
        SERVER_PID=$!
        
        # Wait for server to start
        sleep 5
        
        # Run tests
        ./test-client -endpoint="http://localhost:9000" -bucket="ci-test-bucket"
        
        # Stop server
        kill $SERVER_PID

  release:
    runs-on: ubuntu-latest
    needs: [test, build, integration-test]
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v3

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          porter-linux-amd64/porter-linux-amd64
          porter-linux-arm64/porter-linux-arm64
          porter-darwin-amd64/porter-darwin-amd64
          porter-darwin-arm64/porter-darwin-arm64
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}